//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Microsoft.Playfab.Gaming {

class interop_ConnectedPlayerVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<interop_ConnectedPlayer>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal interop_ConnectedPlayerVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(interop_ConnectedPlayerVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~interop_ConnectedPlayerVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          interop_gsdkPINVOKE.delete_interop_ConnectedPlayerVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public interop_ConnectedPlayerVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (interop_ConnectedPlayer element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public interop_ConnectedPlayer this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(interop_ConnectedPlayer[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(interop_ConnectedPlayer[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, interop_ConnectedPlayer[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<interop_ConnectedPlayer> global::System.Collections.Generic.IEnumerable<interop_ConnectedPlayer>.GetEnumerator() {
    return new interop_ConnectedPlayerVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new interop_ConnectedPlayerVectorEnumerator(this);
  }

  public interop_ConnectedPlayerVectorEnumerator GetEnumerator() {
    return new interop_ConnectedPlayerVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class interop_ConnectedPlayerVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<interop_ConnectedPlayer>
  {
    private interop_ConnectedPlayerVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public interop_ConnectedPlayerVectorEnumerator(interop_ConnectedPlayerVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public interop_ConnectedPlayer Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (interop_ConnectedPlayer)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_Clear(swigCPtr);
  }

  public void Add(interop_ConnectedPlayer x) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_Add(swigCPtr, interop_ConnectedPlayer.getCPtr(x));
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = interop_gsdkPINVOKE.interop_ConnectedPlayerVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = interop_gsdkPINVOKE.interop_ConnectedPlayerVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_reserve(swigCPtr, n);
  }

  public interop_ConnectedPlayerVector() : this(interop_gsdkPINVOKE.new_interop_ConnectedPlayerVector__SWIG_0(), true) {
  }

  public interop_ConnectedPlayerVector(interop_ConnectedPlayerVector other) : this(interop_gsdkPINVOKE.new_interop_ConnectedPlayerVector__SWIG_1(interop_ConnectedPlayerVector.getCPtr(other)), true) {
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public interop_ConnectedPlayerVector(int capacity) : this(interop_gsdkPINVOKE.new_interop_ConnectedPlayerVector__SWIG_2(capacity), true) {
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  private interop_ConnectedPlayer getitemcopy(int index) {
    interop_ConnectedPlayer ret = new interop_ConnectedPlayer(interop_gsdkPINVOKE.interop_ConnectedPlayerVector_getitemcopy(swigCPtr, index), true);
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private interop_ConnectedPlayer getitem(int index) {
    interop_ConnectedPlayer ret = new interop_ConnectedPlayer(interop_gsdkPINVOKE.interop_ConnectedPlayerVector_getitem(swigCPtr, index), false);
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, interop_ConnectedPlayer val) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_setitem(swigCPtr, index, interop_ConnectedPlayer.getCPtr(val));
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(interop_ConnectedPlayerVector values) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_AddRange(swigCPtr, interop_ConnectedPlayerVector.getCPtr(values));
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public interop_ConnectedPlayerVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = interop_gsdkPINVOKE.interop_ConnectedPlayerVector_GetRange(swigCPtr, index, count);
    interop_ConnectedPlayerVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new interop_ConnectedPlayerVector(cPtr, true);
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, interop_ConnectedPlayer x) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_Insert(swigCPtr, index, interop_ConnectedPlayer.getCPtr(x));
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, interop_ConnectedPlayerVector values) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_InsertRange(swigCPtr, index, interop_ConnectedPlayerVector.getCPtr(values));
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_RemoveAt(swigCPtr, index);
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_RemoveRange(swigCPtr, index, count);
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public static interop_ConnectedPlayerVector Repeat(interop_ConnectedPlayer value, int count) {
    global::System.IntPtr cPtr = interop_gsdkPINVOKE.interop_ConnectedPlayerVector_Repeat(interop_ConnectedPlayer.getCPtr(value), count);
    interop_ConnectedPlayerVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new interop_ConnectedPlayerVector(cPtr, true);
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, interop_ConnectedPlayerVector values) {
    interop_gsdkPINVOKE.interop_ConnectedPlayerVector_SetRange(swigCPtr, index, interop_ConnectedPlayerVector.getCPtr(values));
    if (interop_gsdkPINVOKE.SWIGPendingException.Pending) throw interop_gsdkPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
