/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_interop_gsdk_WRAP_H_
#define SWIG_interop_gsdk_WRAP_H_

class SwigDirector_interop_ShutdownCallback : public ShutdownCallback, public Swig::Director {

public:
    SwigDirector_interop_ShutdownCallback();
    virtual void OnShutdown();
    virtual ~SwigDirector_interop_ShutdownCallback();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    void swig_connect_director(SWIG_Callback0_t callbackOnShutdown);

private:
    SWIG_Callback0_t swig_callbackOnShutdown;
    void swig_init_callbacks();
};

class SwigDirector_interop_HealthCallback : public HealthCallback, public Swig::Director {

public:
    SwigDirector_interop_HealthCallback();
    virtual bool OnHealthCheck();
    virtual ~SwigDirector_interop_HealthCallback();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)();
    void swig_connect_director(SWIG_Callback0_t callbackOnHealthCheck);

private:
    SWIG_Callback0_t swig_callbackOnHealthCheck;
    void swig_init_callbacks();
};

class SwigDirector_interop_MaintenanceCallback : public MaintenanceCallback, public Swig::Director {

public:
    SwigDirector_interop_MaintenanceCallback();
    virtual void OnMaintenanceScheduled(time_t newTimeUtc);
    virtual ~SwigDirector_interop_MaintenanceCallback();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(long long);
    void swig_connect_director(SWIG_Callback0_t callbackOnMaintenanceScheduled);

private:
    SWIG_Callback0_t swig_callbackOnMaintenanceScheduled;
    void swig_init_callbacks();
};


#endif
